In [1]:
#Pandas
import pandas as pd

In [ ]:
df = pd.read_csv("/content/crop_yield.csv")

In [ ]:
df.columns

Index(['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='object')

In [ ]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739,794,2051.4,165500.63,539.09,0.420909

In [ ]:
df.tail()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
1985,Arhar/Tur,2006,Kharif,Andhra Pradesh,395644,157669,845.2,50527695.24,87041.68,0.420455
1986,Arhar/Tur,2006,Rabi,Andhra Pradesh,5606,3174,845.2,715942.26,1233.32,0.433333
1987,Bajra,2006,Kharif,Andhra Pradesh,48995,39988,845.2,6257151.45,10778.90,0.737500
1988,Bajra,2006,Rabi,Andhra Pradesh,12081,6986,845.2,1542864.51,2657.82,0.824545
1989,Banana,2006,Whole Year,Andhra Pradesh,50286,1224106,845.2,6422025.06,11062.92,26.198095

In [ ]:
df.shape

(1990, 10)

In [ ]:
df.describe()

,Crop_Year,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
count,1990.000000,1.990000e+03,1.990000e+03,1990.000000,1.990000e+03,1.990000e+03,1990.000000
mean,2001.451256,1.591826e+05,4.322067e+07,1954.082739,1.620221e+07,4.150176e+04,201.424482
std,2.532918,1.196211e+06,4.275042e+08,1246.580875,1.147831e+08,3.652689e+05,1319.233774
min,1997.000000,1.000000e+00,0.000000e+00,315.900000,9.817000e+01,2.100000e-01,0.000000
25%,2000.000000,2.460000e+03,2.693500e+03,1117.700000,2.522836e+05,6.055100e+02,0.549583
50%,2001.000000,1.262000e+04,2.052350e+04,1629.100000,1.316293e+06,3.115225e+03,1.056398
75%,2003.000000,9.185325e+04,1.444862e+05,2354.400000,9.403689e+06,2.223854e+04,2.921806
max,2006.000000,5.080810e+07,6.326000e+09,6552.700000,4.835407e+09,1.575051e+07,13592.127780

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1990 entries, 0 to 1989
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crop             1990 non-null   object
 1   Crop_Year        1990 non-null   int64
 2   Season           1990 non-null   object
 3   State            1990 non-null   object
 4   Area             1990 non-null   int64
 5   Production       1990 non-null   int64
 6   Annual_Rainfall  1990 non-null   float64
 7   Fertilizer       1990 non-null   float64
 8   Pesticide        1990 non-null   float64
 9   Yield            1990 non-null   float64
dtypes: float64(4), int64(3), object(3)
memory usage: 155.6+ KB

In [ ]:
df.isnull().sum()

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [ ]:
df.fillna(df.mean(numeric_only=True), inplace=True)
print(df)

              Crop  Crop_Year       Season           State    Area  \
0         Arecanut       1997  Whole Year            Assam   73814
1        Arhar/Tur       1997  Kharif                Assam    6637
2      Castor seed       1997  Kharif                Assam     796
3         Coconut        1997  Whole Year            Assam   19656
4     Cotton(lint)       1997  Kharif                Assam    1739
...            ...        ...          ...             ...     ...
1985     Arhar/Tur       2006  Kharif       Andhra Pradesh  395644
1986     Arhar/Tur       2006  Rabi         Andhra Pradesh    5606
1987         Bajra       2006  Kharif       Andhra Pradesh   48995
1988         Bajra       2006  Rabi         Andhra Pradesh   12081
1989        Banana       2006  Whole Year   Andhra Pradesh   50286

      Production  Annual_Rainfall   Fertilizer  Pesticide        Yield
0          56708           2051.4   7024878.38   22882.34     0.796087
1           4685           2051.4    631643.29    2057.47     0.710435
2             22           2051.4     75755.32     246.76     0.238333
3      126905000           2051.4   1870661.52    6093.36  5238.051739
4            794           2051.4    165500.63     539.09     0.420909
...          ...              ...          ...        ...          ...
1985      157669            845.2  50527695.24   87041.68     0.420455
1986        3174            845.2    715942.26    1233.32     0.433333
1987       39988            845.2   6257151.45   10778.90     0.737500
1988        6986            845.2   1542864.51    2657.82     0.824545
1989     1224106            845.2   6422025.06   11062.92    26.198095

[1990 rows x 10 columns]

In [ ]:
df.drop_duplicates(inplace=True)
print(df)

              Crop  Crop_Year       Season           State    Area  \
0         Arecanut       1997  Whole Year            Assam   73814
1        Arhar/Tur       1997  Kharif                Assam    6637
2      Castor seed       1997  Kharif                Assam     796
3         Coconut        1997  Whole Year            Assam   19656
4     Cotton(lint)       1997  Kharif                Assam    1739
...            ...        ...          ...             ...     ...
1985     Arhar/Tur       2006  Kharif       Andhra Pradesh  395644
1986     Arhar/Tur       2006  Rabi         Andhra Pradesh    5606
1987         Bajra       2006  Kharif       Andhra Pradesh   48995
1988         Bajra       2006  Rabi         Andhra Pradesh   12081
1989        Banana       2006  Whole Year   Andhra Pradesh   50286

      Production  Annual_Rainfall   Fertilizer  Pesticide        Yield
0          56708           2051.4   7024878.38   22882.34     0.796087
1           4685           2051.4    631643.29    2057.47     0.710435
2             22           2051.4     75755.32     246.76     0.238333
3      126905000           2051.4   1870661.52    6093.36  5238.051739
4            794           2051.4    165500.63     539.09     0.420909
...          ...              ...          ...        ...          ...
1985      157669            845.2  50527695.24   87041.68     0.420455
1986        3174            845.2    715942.26    1233.32     0.433333
1987       39988            845.2   6257151.45   10778.90     0.737500
1988        6986            845.2   1542864.51    2657.82     0.824545
1989     1224106            845.2   6422025.06   11062.92    26.198095

[1990 rows x 10 columns]

In [ ]:
df.columns = df.columns.str.replace(" ", "_")
print(df)

              Crop  Crop_Year       Season           State    Area  \
0         Arecanut       1997  Whole Year            Assam   73814
1        Arhar/Tur       1997  Kharif                Assam    6637
2      Castor seed       1997  Kharif                Assam     796
3         Coconut        1997  Whole Year            Assam   19656
4     Cotton(lint)       1997  Kharif                Assam    1739
...            ...        ...          ...             ...     ...
1985     Arhar/Tur       2006  Kharif       Andhra Pradesh  395644
1986     Arhar/Tur       2006  Rabi         Andhra Pradesh    5606
1987         Bajra       2006  Kharif       Andhra Pradesh   48995
1988         Bajra       2006  Rabi         Andhra Pradesh   12081
1989        Banana       2006  Whole Year   Andhra Pradesh   50286

      Production  Annual_Rainfall   Fertilizer  Pesticide        Yield
0          56708           2051.4   7024878.38   22882.34     0.796087
1           4685           2051.4    631643.29    2057.47     0.710435
2             22           2051.4     75755.32     246.76     0.238333
3      126905000           2051.4   1870661.52    6093.36  5238.051739
4            794           2051.4    165500.63     539.09     0.420909
...          ...              ...          ...        ...          ...
1985      157669            845.2  50527695.24   87041.68     0.420455
1986        3174            845.2    715942.26    1233.32     0.433333
1987       39988            845.2   6257151.45   10778.90     0.737500
1988        6986            845.2   1542864.51    2657.82     0.824545
1989     1224106            845.2   6422025.06   11062.92    26.198095

[1990 rows x 10 columns]

In [ ]:
df['Year']=df['Year'].astype(int)

In [ ]:
df['Crop'].unique()
df['State'].nunique()

9

In [ ]:
df['Crop'].value_counts()
df['Season'].value_counts()

Season
Kharif         716
Whole Year     643
Rabi           471
Summer          96
Autumn          33
Winter          31
Name: count, dtype: int64

In [ ]:
df['Season'] = df['Season'].replace('Kharif ', 'Kharif')
print(df)

              Crop  Crop_Year       Season           State    Area  \
0         Arecanut       1997  Whole Year            Assam   73814
1        Arhar/Tur       1997  Kharif                Assam    6637
2      Castor seed       1997  Kharif                Assam     796
3         Coconut        1997  Whole Year            Assam   19656
4     Cotton(lint)       1997  Kharif                Assam    1739
...            ...        ...          ...             ...     ...
1985     Arhar/Tur       2006  Kharif       Andhra Pradesh  395644
1986     Arhar/Tur       2006  Rabi         Andhra Pradesh    5606
1987         Bajra       2006  Kharif       Andhra Pradesh   48995
1988         Bajra       2006  Rabi         Andhra Pradesh   12081
1989        Banana       2006  Whole Year   Andhra Pradesh   50286

      Production  Annual_Rainfall   Fertilizer  Pesticide        Yield
0          56708           2051.4   7024878.38   22882.34     0.796087
1           4685           2051.4    631643.29    2057.47     0.710435
2             22           2051.4     75755.32     246.76     0.238333
3      126905000           2051.4   1870661.52    6093.36  5238.051739
4            794           2051.4    165500.63     539.09     0.420909
...          ...              ...          ...        ...          ...
1985      157669            845.2  50527695.24   87041.68     0.420455
1986        3174            845.2    715942.26    1233.32     0.433333
1987       39988            845.2   6257151.45   10778.90     0.737500
1988        6986            845.2   1542864.51    2657.82     0.824545
1989     1224106            845.2   6422025.06   11062.92    26.198095

[1990 rows x 10 columns]

In [ ]:
df.rename(columns={'Crop_Year':'Year'}, inplace=True)
print(df)

              Crop  Year       Season           State    Area  Production  \
0         Arecanut  1997  Whole Year            Assam   73814       56708
1        Arhar/Tur  1997  Kharif                Assam    6637        4685
2      Castor seed  1997  Kharif                Assam     796          22
3         Coconut   1997  Whole Year            Assam   19656   126905000
4     Cotton(lint)  1997  Kharif                Assam    1739         794
...            ...   ...          ...             ...     ...         ...
1985     Arhar/Tur  2006  Kharif       Andhra Pradesh  395644      157669
1986     Arhar/Tur  2006  Rabi         Andhra Pradesh    5606        3174
1987         Bajra  2006  Kharif       Andhra Pradesh   48995       39988
1988         Bajra  2006  Rabi         Andhra Pradesh   12081        6986
1989        Banana  2006  Whole Year   Andhra Pradesh   50286     1224106

      Annual_Rainfall   Fertilizer  Pesticide        Yield
0              2051.4   7024878.38   22882.34     0.796087
1              2051.4    631643.29    2057.47     0.710435
2              2051.4     75755.32     246.76     0.238333
3              2051.4   1870661.52    6093.36  5238.051739
4              2051.4    165500.63     539.09     0.420909
...               ...          ...        ...          ...
1985            845.2  50527695.24   87041.68     0.420455
1986            845.2    715942.26    1233.32     0.433333
1987            845.2   6257151.45   10778.90     0.737500
1988            845.2   1542864.51    2657.82     0.824545
1989            845.2   6422025.06   11062.92    26.198095

[1990 rows x 10 columns]

In [ ]:
df.columns

Index(['Crop', 'Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='object')

In [ ]:
df.groupby('State')['Production'].sum()

State
Andhra Pradesh     5654673164
Assam              1301082662
Goa                 738630733
Karnataka          9798297030
Kerala            50985985148
Meghalaya             5547833
Puducherry          107428852
Tamil Nadu        14544150680
West Bengal        2873343154
Name: Production, dtype: int64

In [ ]:
df.sample(5)

,Crop,Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
778,Mesta,2001,Kharif,Andhra Pradesh,78942,671542,928.4000,8062346.46,20524.92,8.370909
1032,Linseed,2002,Rabi,Andhra Pradesh,4070,1238,648.1000,385306.90,1017.50,0.322857
856,Castor seed,2001,Kharif,Karnataka,21799,16137,1002.9000,2226331.87,5667.74,0.704000
260,Tapioca,1998,Whole Year,Kerala,112774,2630155,3151.5000,11142071.20,32704.46,25.517857
137,Onion,1998,Kharif,Puducherry,26,429,1434.5875,2568.80,7.54,16.500000

In [ ]:
df.corr(numeric_only=True)

,Year,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
Year,1.000000,-0.037588,0.009821,-0.226590,-0.030700,-0.048575,-0.010434
Area,-0.037588,1.000000,0.043543,-0.045803,0.999311,0.998041,0.005345
Production,0.009821,0.043543,1.000000,0.014476,0.047010,0.035574,0.500945
Annual_Rainfall,-0.226590,-0.045803,0.014476,1.000000,-0.048827,-0.036603,-0.019188
Fertilizer,-0.030700,0.999311,0.047010,-0.048827,1.000000,0.995437,0.006178
Pesticide,-0.048575,0.998041,0.035574,-0.036603,0.995437,1.000000,0.003437
Yield,-0.010434,0.005345,0.500945,-0.019188,0.006178,0.003437,1.000000